config/routes.rb
Grabbit2::Application.routes.draw do
  resources :coupons

  resources :profiles

  resources :orders

  resources :deals

devise_for :users

  root :to => 'deals#show', :id => 1

   match ':controller(/:action(/:id(.:format)))'
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  # GET /coupons
  # GET /coupons.xml
  def index
    @coupons = Coupon.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @coupons }
    end
  end

  # GET /coupons/1
  # GET /coupons/1.xml
  def show
    @coupon = Coupon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @coupon }
    end
  end

  # GET /coupons/new
  # GET /coupons/new.xml
  def new
    @coupon = Coupon.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @coupon }
    end
  end

  # GET /coupons/1/edit
  def edit
    @coupon = Coupon.find(params[:id])
  end

  # POST /coupons
  # POST /coupons.xml
  def create
    @coupon = Coupon.new(params[:coupon])

    respond_to do |format|
      if @coupon.save
        format.html { redirect_to(@coupon, :notice => 'Coupon was successfully created.') }
        format.xml  { render :xml => @coupon, :status => :created, :location => @coupon }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @coupon.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /coupons/1
  # PUT /coupons/1.xml
  def update
    @coupon = Coupon.find(params[:id])

    respond_to do |format|
      if @coupon.update_attributes(params[:coupon])
        format.html { redirect_to(@coupon, :notice => 'Coupon was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @coupon.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1
  # DELETE /coupons/1.xml
  def destroy
    @coupon = Coupon.find(params[:id])
    @coupon.destroy

    respond_to do |format|
      format.html { redirect_to(coupons_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/views/coupons/_form.html.erb
<%= form_for(@coupon) do |f| %>
  <% if @coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% @coupon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :coupon_number %><br />
    <%= f.text_field :coupon_number %>
  </div>

  <div class="field">
    <%= f.label :order_id %><br />
    <%= f.text_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :purchase_date %><br />
    <%= f.datetime_select :purchase_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coupons/edit.html.erb
<h1>Editing coupon</h1>

<%= render 'form' %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/index.html.erb
<h1>Listing coupons</h1>


<%= link_to "Today's Deal", deal_path(1) %>

<table>
	<tr>
		    <th>Deal</th>
    <th>Coupon Number</th>
    <th>Order</th>
    <th>Purchase Date</th>
        <th>Expiration Date</th>
               <% if can? :update,@coupon  %>
	<th>Status</th>
<% end %>    
	<th></th>
    <th></th>
    <th></th>
  </tr>



  <% @coupons.each do |coupon| %>
	  <% if current_user.role == 'admin' || coupon.order.user_id == current_user.id %>
	  
 <tr>
	 <td><%=link_to coupon.order.deal.title, coupon.order.deal %></td>
    <td><%= coupon.coupon_number %></td>
    <td><%= coupon.order_id %></td>
    <td><%= coupon.purchase_date %></td>
        <td><%= coupon.order.deal.expiration_date %></td>
           <% if can? :update, coupon  %>
    <td><%= coupon.status %></td>
<% end %>
        <% if can? :update, coupon  %>
    <td><%= link_to 'Show', coupon %></td>


    <td><%= link_to 'Edit', edit_coupon_path(coupon) %></td>
       <td><%= link_to 'Destroy', coupon, :confirm => 'Are you sure?', :method => :delete %></td>
     <% end %>   

  </tr>

  <% end %>
<% end %>
</table>

<br />

<%  if current_user %>
<%= link_to 'Profile', edit_profile_path(current_user) %>
<% end %>
<%= link_to 'Coupons', coupons_path %>

app/views/coupons/new.html.erb
<h1>New coupon</h1>

<%= render 'form' %>

<%= link_to 'Back', coupons_path %>

app/views/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Coupon number:</b>
  <%= @coupon.coupon_number %>
</p>

<p>
  <b>Order:</b>
  <%= @coupon.order_id %>
</p>

<p>
  <b>Purchase date:</b>
  <%= @coupon.purchase_date %>
</p>

<p>
  <b>Status:</b>
  <%= @coupon.status %>
</p>


<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>