config/routes.rb
Grabbit2::Application.routes.draw do
  resources :coupons

  resources :profiles

  resources :orders

  resources :deals

devise_for :users

  root :to => 'deals#show', :id => 1

   match ':controller(/:action(/:id(.:format)))'
end

app/models/deal.rb
class Deal < ActiveRecord::Base
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  # GET /deals
  # GET /deals.xml
  def index
    @deals = Deal.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @deals }
    end
  end

  # GET /deals/1
  # GET /deals/1.xml
  def show
    @deal = Deal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @deal }
    end
  end

  # GET /deals/new
  # GET /deals/new.xml
  def new
    @deal = Deal.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
  end

  # POST /deals
  # POST /deals.xml
  def create
    @deal = Deal.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to(@deal, :notice => 'Deal was successfully created.') }
        format.xml  { render :xml => @deal, :status => :created, :location => @deal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @deal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /deals/1
  # PUT /deals/1.xml
  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to(@deal, :notice => 'Deal was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @deal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.xml
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to(deals_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<%= form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :fine_print %><br />
    <%= f.text_field :fine_print %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %><br />
    <%= f.datetime_select :expiration_date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<h1>Listing deals</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Value</th>
    <th>Description</th>
    <th>Fine print</th>
    <th>Expiration date</th>
    <th>Start time</th>
    <th>End time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deals.each do |deal| %>
  <tr>
    <td><%= deal.title %></td>
    <td><%= deal.price %></td>
    <td><%= deal.value %></td>
    <td><%= deal.description %></td>
    <td><%= deal.fine_print %></td>
    <td><%= deal.expiration_date %></td>
    <td><%= deal.start_time %></td>
    <td><%= deal.end_time %></td>
    <td><%= link_to 'Show', deal %></td>
    <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
    <td><%= link_to 'Destroy', deal, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deal', new_deal_path %>

app/views/deals/new.html.erb
<h1>New deal</h1>

<%= render 'form' %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>





<p>
  <b>Title:</b>
  <%= @deal.title %>
</p>

<p>
  <b>Price:</b>
  <%= @deal.price %>
</p>

<p>
  <b>Value:</b>
  <%= @deal.value %>
</p>

<p>
  <b>Description:</b>
  <%= @deal.description %>
</p>

<p>
  <b>Fine print:</b>
  <%= @deal.fine_print %>
</p>

<p>
  <b>Expiration date:</b>
  <%= @deal.expiration_date %>
</p>

<p>
  <b>Start time:</b>
  <%= @deal.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @deal.end_time %>
</p>


    <% if can? :update, @deal  %>
	    <%= link_to 'Edit', edit_deal_path(@deal) %> |

	    <%= link_to 'Back', deals_path %>
	        <% end %>